name: example
dependencies:
  hive: any
dev_dependencies:
  build_runner: any
  hive_generator:
    path: ..
environment:
  sdk: ">=2.15.0 <4.0.0"
dependency_overrides:
  hive:
    path: ../../hive
  hive_generator:
    path: ..